version: '3'

x-cimple: &common
  build:
    context: .
    args:
      DEFAULT_HOST: server
  image: egortensin/cimple
  restart: always

services:
  server:
    <<: *common
    ports:
      - 5556
  worker1:
    <<: *common
    command: ["cimple-worker"]
    depends_on: [server]
  worker2:
    <<: *common
    command: ["cimple-worker"]
    depends_on: [server]
  client:
    <<: *common
    command: []
    depends_on: [server]
    entrypoint: ["cimple-client"]
    restart: 'no'
