version: '3.7'

x-cimple: &common
  build:
    context: .
    args:
      DEFAULT_HOST: server
  image: egortensin/cimple
  restart: always

services:
  server:
    <<: *common
    ports:
      - 5556
    volumes:
      - db:/var/lib/cimple
  worker1:
    <<: *common
    command: ["cimple-worker"]
    depends_on: [server]
  worker2:
    <<: *common
    command: ["cimple-worker"]
    depends_on: [server]
  client:
    <<: *common
    command: ["--version"]
    depends_on: [server]
    entrypoint: ["cimple-client"]
    restart: 'no'

volumes:
  db:
